---

- name: Install and manage WordPress instances
  hosts: 'wordpress'
  collections: ['debops.debops', 'debops.roles01',
                 'debops.roles02', 'debops.roles03']
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  pre_tasks:

    - name: Prepare pki environment
      ansible.builtin.import_role:
        name: 'pki'
        tasks_from: 'main_env'
      vars:
        pki_dependent_realms: 
          - '{{ wordpress__pki__dependent_realms }}'
      tags: [ 'role::pki', 'role::pki:secret', 'role::secret', 'role::apt_preferences']

    - name: Prepare sshd environment
      ansible.builtin.import_role:
        name: 'sshd'
        tasks_from: 'main_env'
      tags: [ 'role::sshd', 'role::ldap' ]

    - name: Prepare php environment
      ansible.builtin.import_role:
        name: 'php'
        tasks_from: 'main_env'
      tags: [ 'role::php', 'role::php:env', 'role::apt_preferences', 'role::logrotate' ]
      # tags: [ 'role::', 'role::ldap' ]

    - name: Prepare redis_server environment
      ansible.builtin.import_role:
        name: 'redis_server'
        tasks_from: 'main_env'
      tags: [ 'role::redis_server', 'role::redis_server:env', 'role::apt_preferences', 'role::ferm' ]

    - name: Prepare sysfs environment
      ansible.builtin.import_role:
        name: 'sysfs'
        tasks_from: 'main_env'
      tags: [ 'role::sysfs', 'role::sysfs:env', 'role::secret', 'role::pki' ]

    # - name: Prepare elasticsearch environment
    #   ansible.builtin.import_role:
    #     name: 'elasticsearch'
    #     tasks_from: 'main_env'
    #   tags: [ 'role::elasticsearch', 'role::elasticsearch:env', 'role:elasticsearch:config', 'role::apt_preferences', 'role::pki', 'role::secret' ]

    # - role: pki/env
    #   tags: [ 'role::pki', 'role::pki:env', 'role::apt_preferences', 'role::secret' ]
    #   pki_dependent_realms:
    #     - '{{ wordpress__pki__dependent_realms }}'
    #   when: wordpress__ssl|bool
    #
    # - role: php/env
    #   tags: [ 'role::php', 'role::php:env', 'role::apt_preferences', 'role::logrotate' ]
    #
    # - role: redis_server/env
    #   tags: [ 'role::redis_server', 'role::redis_server:env', 'role::apt_preferences', 'role::ferm' ]
    #
    # - role: sysfs/env
    #   tags: [ 'role::sysfs', 'role::sysfs:env', 'role::secret', 'role::pki' ]
  
  roles:

    # Environment roles
    - role: wordpress/env
      tags: [ 'role::mariadb', 'role::pki', 'role::users' ]



    # Configuration roles
    #

    - role: keyring
      tags: [ 'role::keyring', 'skip::keyring'] # , 'role::elastic_co' 
      # keyring__dependent_apt_keys:
      #   - '{{ elastic_co__keyring__dependent_apt_keys }}'

    - role: apt_preferences
      tags: [ 'role::apt_preferences', 'skip::apt_preferences',  'role::nginx', 'role::php',  'role::redis_server' ] #  'role::elasticsearch', 'role::java',
      apt_preferences__dependent_list:
        # - '{{ elastic_co__apt_preferences__dependent_list }}'
        # - '{{ java__apt_preferences__dependent_list }}'
        - '{{ nginx__apt_preferences__dependent_list }}'
        - '{{ php__apt_preferences__dependent_list }}'
        - '{{ redis_server__apt_preferences__dependent_list }}'

    - role: etc_services
      tags: [ 'role::etc_services', 'skip::etc_services', 'role::redis_server' ] # , 'role::elasticsearch'
      etc_services__dependent_list:
        # - '{{ elasticsearch__etc_services__dependent_list }}'
        - '{{ redis_server__etc_services__dependent_list }}'

    - role: ferm
      tags: [ 'role::ferm', 'skip::ferm', 'role::nginx' ] #  'role::elasticsearch',
      ferm__dependent_rules:
        # - '{{ elasticsearch__ferm__dependent_rules }}'
        - '{{ nginx__ferm__dependent_rules }}'

    # - role: java
    #   tags: [ 'role::java', 'skip::java', 'role::elasticsearch' ]

    - role: logrotate
      tags: [ 'role::logrotate', 'skip::logrotate', 'role::php' ]
      logrotate__dependent_config:
        - '{{ php__logrotate__dependent_config }}'

    - role: python
      tags: [ 'role::python', 'skip::python', 'role::mariadb', 'role::mariadb_server', 'role::redis_server' ]
      python__dependent_packages3:
        - '{{ mariadb__python__dependent_packages3 }}'
        - '{{ mariadb_server__python__dependent_packages3 }}'
        - '{{ redis_server__python__dependent_packages3 }}'
      python__dependent_packages2:
        - '{{ mariadb__python__dependent_packages2 }}'
        - '{{ mariadb_server__python__dependent_packages2 }}'
        - '{{ redis_server__python__dependent_packages2 }}'

    - role: secret
      tags: [ 'role::secret', 'skip::secret',  'role::pki', 'role::sysfs' ] # 'role::elasticsearch',
      secret_directories:
        - '{{ pki_env_secret_directories | d([]) }}'
        #        - '{{ elasticsearch__secret__directories | d([]) }}'
        - '{{ sysfs__secret__directories | d([]) }}'
        - '{{ wordpress__secret__directories }}'

    - role: sysctl
      tags: [ 'role::sysctl', 'skip::sysctl', 'role::redis_server' ] # , 'role::elasticsearch'
      sysctl__dependent_parameters:
        # - '{{ elasticsearch__sysctl__dependent_parameters }}'
        - '{{ redis_server__sysctl__dependent_parameters }}'

    - role: sysfs
      tags: [ 'role::sysfs', 'skip::sysfs', 'role::redis_server' ]
      sysfs__dependent_attributes:
        - '{{ redis_server__sysfs__dependent_attributes }}'

    - role: swapfile
      tags: [ 'role::swapfile', 'skip::swapfile' ]

    - role: users
      tags: [ 'role::users', 'skip::users' ]
      users__dependent_accounts: '{{ wordpress__users__dependent_accounts }}'


    # Database roles
    #

    - role: mariadb_server
      tags: [ 'role::mariadb_server', 'skip::mariadb_server' ]

    - role: mariadb
      tags: [ 'role::mariadb', 'skip::mariadb' ]
      mariadb__dependent_databases:
        - '{{ wordpress__mariadb__dependent_databases }}'
      mariadb__dependent_users:
        - '{{ wordpress__mariadb__dependent_users }}'


    # Elasticsearch roles
    #

    # - role: elastic_co
    #   tags: [ 'role::elastic_co', 'skip::elastic_co', 'role::elasticsearch' ]
    #   elastic_co__dependent_packages:
    #     - '{{ elasticsearch__elastic_co__dependent_packages }}'
    #
    # - role: elasticsearch
    #   tags: [ 'role::elasticsearch', 'skip::elasticsearch' ]

    # Web server roles
    #

    - role: fail2ban
      tags: [ 'role::fail2ban', 'skip::fail2ban' ]
      fail2ban_action: '{{ wordpress__fail2ban__default_action }}'
      fail2ban_actions:
        - '{{ wordpress__fail2ban__actions }}'
      fail2ban_bantime: '{{ wordpress__fail2ban__default_bantime }}'
      fail2ban_custom_actions: '{{ wordpress__fail2ban__custom_actions }}'
      fail2ban_dependent_jails:
        - '{{ wordpress__fail2ban__dependent_jails }}'
      fail2ban_filters:
        - '{{ wordpress__fail2ban__filters }}'
      fail2ban_findtime: '{{ wordpress__fail2ban__default_findtime }}'
      fail2ban_ignoreip: '{{ wordpress__fail2ban__ignoreip }}'
      fail2ban_jails: []
      fail2ban_loglevel: '{{ wordpress__fail2ban__loglevel }}'
      fail2ban_maxretry: '{{ wordpress__fail2ban__default_maxretry }}'

    - role: php
      tags: [ 'role::php', 'skip::php' ]
      php__default_pools: []
      php__dependent_packages:
        - '{{ wordpress__php__dependent_packages }}'
      php__dependent_pools:
        - '{{ wordpress__php__dependent_pools }}'
      php__ini_memory_limit: '{{ wordpress__php__memory_limit }}'
      php__ini_post_max_size: '{{ wordpress__php__post_max_size }}'

    - role: nginx
      tags: [ 'role::nginx', 'skip::nginx' ]
      nginx_acme: False
      nginx_acme_root: '{{ wordpress__nginx__acme_root }}'
      nginx__default_servers: []
      nginx__default_upstreams: []
      nginx__dependent_servers:
        - '{{ wordpress__nginx__dependent_servers }}'
      nginx__dependent_upstreams:
        - '{{ wordpress__nginx__dependent_upstreams }}'
      nginx__internal_servers: []
      nginx_pki_realm: '{{ wordpress__nginx__pki_realm }}'
      nginx_user: '{{ wordpress__nginx__user }}'
      nginx_webroot_create: False
      nginx_www: '{{ wordpress__nginx__www }}'

    - role: pki
      tags: [ 'role::pki', 'skip::pki' ]
      pki_acme_group: '{{ wordpress__pki__acme_group }}'
      pki_acme_user: '{{ wordpress__pki__acme_user }}'
      pki_dependent_realms:
        - '{{ wordpress__pki__dependent_realms }}'
      pki_host_private_files: "{{ wordpress__pki__private_files if wordpress__ssl_provider == 'manual' else [] }}"
      pki_host_public_files: "{{ wordpress__pki__public_files if wordpress__ssl_provider == 'manual' else [] }}"
      when: wordpress__ssl|bool

    - role: redis_server
      tags: [ 'role::redis_server', 'skip::redis_server' ]
      redis_server__auth_password: '{{ wordpress__redis_server__auth_password }}'

    - role: varnish
      tags: [ 'role::varnish', 'skip::varnish' ]
      varnish__listen: '{{ wordpress__varnish__listen }}'
      varnish__backends: [ '{{ wordpress__varnish__backend }}' ]
      varnish__add_ban_lurker_headers: '{{ wordpress__varnish__add_ban_lurker_headers }}'
      varnish__normalize_query_parameters: '{{ wordpress__varnish__normalize_query_parameters }}'
      varnish__purge_allow: '{{ wordpress__varnish__purge_allow }}'
      varnish__purge_conditions: '{{ wordpress__varnish__purge_conditions_default | combine(wordpress__varnish__purge_conditions) }}'
      varnish__vcl_backend_response_conditions: '{{ wordpress__varnish__vcl_backend_response_conditions_default | combine(wordpress__varnish__vcl_backend_response_conditions) }}'
      varnish__vcl_recv_conditions: '{{ wordpress__varnish__vcl_recv_conditions_default | combine(wordpress__varnish__vcl_recv_conditions) }}'
      varnish__vcl_recv_remove_cookies: '{{ wordpress__varnish__vcl_recv_remove_cookies }}'

    - role: wpcli
      tags: [ 'role::wpcli', 'skip::wpcli' ]

    - role: wordpress
      tags: [ 'role::wordpress', 'skip::wordpress' ]
